### API USUARIO GET

GET http://localhost:8080/api/v1/usuarios

### API POSTAGEM GET

GET http://localhost:8080/api/v1/postagens

### API CLIENTE POST

POST http://localhost:8080/api/v1/usuarios
Content-Type: application/json

{
    "nome": "zezinho",
    "curso": "sistemas",
    "semestreTurma": "5an",
    "telefone": "88888903",
    "email": "ze@gmail.com",
    "senha": "ze123",
    "bio": "oi",
    "atletica": "atenum",
    "dataNascimento": "2000-04-22"
}

### API POSTAGEM POST

POST http://localhost:8080/api/v1/postagens
Content-Type: application/json

{
    "autor": {
        "id": 1,
        "nome": "zezinho",
        "curso": "sistemas",
        "semestreTurma": "5an",
        "telefone": "88888903",
        "email": "kaue@gmail.com",
        "senha": "ze123",
        "bio": "oi",
        "atletica": "atenum",
        "dataNascimento": "2000-04-22"
    },
    "texto": "oi",
    "curtidas": []
}

### API CLIENTE PUT

PUT http://localhost:8080/api/v1/usuarios
Content-Type: application/json

{
    "nome": "zezinho da gama",
    "curso": "sistemas",
    "semestreTurma": "5an",
    "telefone": "88888903",
    "email": "ze@gmail.com",
    "senha": "ze123",
    "bio": "oi",
    "atletica": "atenum",
    "dataNascimento": "2000-04-22"
}

### API CLIENTE DELETE

DELETE http://localhost:8080/api/v1/usuarios/3
